services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    LukasBableck\ContaoInstantIndexingBundle\:
        resource: ../src
        exclude: ../src/{Resources}
    LukasBableck\ContaoInstantIndexingBundle\EventListener\:
        resource: ../src/EventListener
        public: true