services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Lukasbableck\ContaoInstantIndexingBundle\:
        resource: ../src
    Lukasbableck\ContaoInstantIndexingBundle\Client\:
        resource: ../src/Client
        public: true