services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    LukasBableck\ContaoInstantIndexingBundle\EventListener\:
        resource: ../src/EventListener
        public: true